spring:
  application:
    name: springboot3
  datasource:
    url: jdbc:mysql://localhost:3306/spring3?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      pool-name: Springboot3HikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    host: 10.5.2.223 # 地址
    port: 6379 # 端口
    # 通用配置
    password: 6j@mhgjfcO # 密码
    database: 15 # 指定数据库序号
    ssl: false # 是否启用SSL
    connect-timeout: 1000 # 连接超时时间（毫秒）
    timeout: 1000 # 操作超时时间（毫秒）
    client-type: lettuce # 驱动类型
    # 连接池配置
    lettuce:
      pool:
        min-idle: 1 # 最小空闲连接（默认0）
        max-idle: 8 # 最大空闲连接（默认8）
        max-active: 16 # 最大连接数（默认8，使用负值表示没有限制）
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/xml/*.xml

async:
  executor:
    thread:
      core_pool_size: 5 # 配置核心线程数
      max_pool_size: 5 # 配置最大线程数
      queue_capacity: 999 # 配置队列大小
      keep_alive_seconds: 30 # 配置线程最大空闲时间
      name:
        prefix: spirng3-async- # 配置线程池中的线程的名称前缀

springdoc:
  packagesToScan: com.zhejianglab.spring3web.controller
  swagger-ui:
    disable-swagger-default-url: off
    enabled: true
